// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDku3r521N43TGJ_FGkjZ_t4jbSHY4gfrU',
    appId: '1:875325893345:web:18494933bf5f86acaba5a0',
    messagingSenderId: '875325893345',
    projectId: 'studyscapescu',
    authDomain: 'studyscapescu.firebaseapp.com',
    storageBucket: 'studyscapescu.firebasestorage.app',
    measurementId: 'G-YFY49WVXS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-sDUlYaN2sxmuad87yDyY-2lxL1Fa8XU',
    appId: '1:875325893345:android:17c0de72c9873d11aba5a0',
    messagingSenderId: '875325893345',
    projectId: 'studyscapescu',
    storageBucket: 'studyscapescu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxYLtTycKFt2dEtnG0jzGJbUN9_sypOnY',
    appId: '1:875325893345:ios:89796eb3c1633368aba5a0',
    messagingSenderId: '875325893345',
    projectId: 'studyscapescu',
    storageBucket: 'studyscapescu.firebasestorage.app',
    iosBundleId: 'com.example.studyscape',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxYLtTycKFt2dEtnG0jzGJbUN9_sypOnY',
    appId: '1:875325893345:ios:89796eb3c1633368aba5a0',
    messagingSenderId: '875325893345',
    projectId: 'studyscapescu',
    storageBucket: 'studyscapescu.firebasestorage.app',
    iosBundleId: 'com.example.studyscape',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDku3r521N43TGJ_FGkjZ_t4jbSHY4gfrU',
    appId: '1:875325893345:web:6a4faf55ecac270daba5a0',
    messagingSenderId: '875325893345',
    projectId: 'studyscapescu',
    authDomain: 'studyscapescu.firebaseapp.com',
    storageBucket: 'studyscapescu.firebasestorage.app',
    measurementId: 'G-Z4PS1E14EB',
  );
}
